name: demo2
description: "Goida AI - iOS Finance Tracker + AI Chat + Messenger"
publish_to: 'none'
version: 0.2.0+2

environment:
  sdk: ^3.11.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  dio: ^5.4.1
  provider: ^6.1.2
  google_sign_in: ^6.2.1
  image_picker: ^1.0.7
  file_picker: ^8.0.0
  shared_preferences: ^2.5.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  web_socket_channel: ^2.4.0
  lottie: ^3.0.0
  flutter_staggered_animations: ^1.1.1
  animated_text_kit: ^4.2.2
  http: ^1.2.0
  http_parser: ^4.0.2
  fl_chart: ^0.69.0
  cupertino_icons: ^1.0.8
  qr_flutter: ^4.1.0
  walletconnect_dart: ^0.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  mockito: ^5.4.4
  build_runner: ^2.4.8

flutter:
  generate: true
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/iconwhite.jpg"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "path/to/image.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "path/to/image.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "path/to/image.png"
